# ----------------------------------------------------------------------- #
#                                                                         #
#                               YMAL文件语法                               #
#                       http://medai.icu/thread/677                       #
#                                                                         #
# ----------------------------------------------------------------------- #
# 你自己的影像数据【目录】
radio_dir: C:\Users\onekey\Desktop\demo
# 带有group分组的label文件位置
label_file: split_info\label-RND-0.csv
# 临床数据位置，不要有label和group信息
clinic_file: C:\Users\onekey\Desktop\demo\clinical.csv
# 瘤内的Mask中的ID
intra_mask_id: 1
# 一般不用动
task_column: label
dataset_column: group
# 衡量显著性的阈值，一般别动！
pvalue: 0.05
# 是否使用分形维数特征，默认是False，当ROI比较小或者是单层(超声数据)的时候会导致计算失败。
with_fd: False
# 是否使用SMOTE，解决样本不均衡的问题。
use_smote: False
# 提取特征的配置文件，在custom_settings文件夹里面按需选择
extractor_settings: 
# 使用MRMR模型筛选特征, 不输入数据的时候，不使用mRMR，默认不使用
mrmr_sel_feature_num: 30
ml_models: [LR, SVM, RandomForest, ExtraTrees, XGBoost, LightGBM, nb, AdaBoost, GradientBoost]
# 对比不同算法
compare_algos: [Radiomics_LR, Radiomics_SVM, Radiomics_RandomForest, Radiomics_XGBoost]
# 汇总的模型
summary_models: [Clinic, Radiomics, Combined]
subsets: [train, test]
# 筛选的模型
sel_model: 
  Clinic: LR
  Radiomics: LR
font.size: 12
# 是否显示视频
DISABLE_VIDEO: True
PAPER_TMP: Radiomics